# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PerlIO-via-MD5
version:      0.06
version_from: lib/PerlIO/via/MD5.pm
installdirs:  site
requires:
    Digest::MD5:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
